project:
  type: book
  output-dir: docs

book:
  title: "Perceptual Disfluency and Recognition Memory: A Mathematical and Computational Analysis of RT Distributions"
  author: "Jason Geller"
  date: 'Updated:`r Sys.Date()`'
  chapters:
    - index.qmd
    - intro.qmd
    - expt1a.qmd
    - Experiment2.qmd
    - Experiment3.qmd
    - General_Discussion.qmd

format:
      html:
        self-contained: true
        anchor-sections: true
        code-tools: true
        code-fold: true
        fig-width: 12
        fig-height: 8
        code-block-bg: "#f1f3f5"
        code-block-border-left: "#31BAE9"
        mainfont: Source Sans Pro
        theme: journal
        toc: true
comments:
      hypothesis: true

execute:
      warning: false
      message: false
